Update setup.py
JarbasSkills/skill-icanhazdadjokes pull request #7
Opened 2023-09-05 17:50 UTC by JarbasAl

2023-09-05 17:51 UTC, mikejgray requested changes
Consider a different name, as there's talk of including other joke sources

2023-09-06 11:54 UTC, builderjer commented
I would agree with mike, a different name, but not sure what it would be.

2023-09-06 23:11 UTC, emphasize commented
"Accidentally funny" 😛 
A name not taking itself too serious and no meme-y name. But maybe i'm too old for this.

2023-09-13 01:59 UTC, mikejgray approved these changes

2023-09-13 11:35 UTC, builderjer approved these changes

2023-09-13 12:23 UTC, merged